/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define GPIO_BASE_ADDRESS 0x40020C00
#define RCC_BASE_ADDRESS  0x40023800
#define AHB1ENR_OFFSET 0x30
#define POWER_ENABLE 0x08
#define OUTPUT_DATA_REGISTER 0x14


int main(void)
{
	//enabling
	//reason of the below typecasting is
	//Treat this specific memory address as the starting point of a RCC_AHB1ENR_t structure
	RCC_AHB1ENR_t volatile *const rcc_base = (RCC_AHB1ENR_t *)(RCC_BASE_ADDRESS + AHB1ENR_OFFSET);
	//GPIO PORT mode register
	GPIO_MODER_t volatile *const gcc_base = (GPIO_MODER_t *)(GPIO_BASE_ADDRESS);
	//GPIO Output data register
	GPIO_ODR_t volatile *const odr_base = (GPIO_ODR_t *)(GPIO_BASE_ADDRESS + OUTPUT_DATA_REGISTER);
	rcc_base->GPIODEN = 1;
	gcc_base->MODER12 = 1;
	while (1) {
		odr_base -> ODR12 =1;
		for(volatile uint32_t i=0; i<300000; i++);
		odr_base -> ODR12 = 0;
		for(volatile uint32_t i=0; i<300000; i++);
	}

	return 1;
}
